print(' dont add A at the beging of any of these: example "a fish"')
animal = input("type the first animal that comes to your head\n")
verb = input("type the first verb that comes to your mind\n")
big_object = input("think of a big object\n")
small_object = input('think of a small object\n')
sit = input("type a object that's soft and you can sit on\n")
drink = input("think of a drink\n")
print ('you are walking your '+animal+" when your "+animal+" "+verb+ " up a "+big_object+", and triped over a small "+small_object+" and fell and hurt it's knee. then your "+animal+" fell of the "+big_object+" and landed on a "+sit+" your "+animal+" finds a "+drink+" on the floor.")
print ("the end")